# Generated by Django 5.0.6 on 2024-06-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('topic', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'talha',
            },
        ),
        migrations.CreateModel(
            name='online_judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_name', models.CharField(max_length=20)),
                ('total_problem', models.IntegerField()),
                ('handle_name', models.CharField(max_length=10)),
            ],
        ),
    ]
